--------------------------------------------------------
--  File created - Saturday-June-12-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACTION_LOG
--------------------------------------------------------

  CREATE TABLE "DEMO"."ACTION_LOG" 
   (	"LOG_ID" VARCHAR2(120 CHAR), 
	"ACTION" VARCHAR2(1500 CHAR), 
	"IP_ADDRESS" VARCHAR2(20 CHAR), 
	"LOG_TIME" TIMESTAMP (6), 
	"USER_ID" VARCHAR2(120 CHAR), 
	"RESULT" VARCHAR2(1500 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table APPLICATIONS
--------------------------------------------------------

  CREATE TABLE "DEMO"."APPLICATIONS" 
   (	"APP_ID" VARCHAR2(120 CHAR), 
	"APP_CODE" VARCHAR2(50 CHAR), 
	"APP_NAME" VARCHAR2(1000 CHAR), 
	"DESCRIPTION" VARCHAR2(1000 CHAR), 
	"SECURITY_OPTION" NUMBER(2,0), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AREA
--------------------------------------------------------

  CREATE TABLE "DEMO"."AREA" 
   (	"AREA_ID" VARCHAR2(120 CHAR), 
	"NAME" VARCHAR2(300 CHAR), 
	"PARENT_ID" VARCHAR2(120 CHAR), 
	"PROVINCE_CODE" VARCHAR2(50 CHAR), 
	"STATUS" NUMBER(1,0), 
	"TYPE" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTO_SYN_DATA
--------------------------------------------------------

  CREATE TABLE "DEMO"."AUTO_SYN_DATA" 
   (	"DB_ID" VARCHAR2(120 CHAR), 
	"SCN_LAST_SYN" NUMBER(10,0), 
	"TB_ID" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTO_SYN_DB_PARAM
--------------------------------------------------------

  CREATE TABLE "DEMO"."AUTO_SYN_DB_PARAM" 
   (	"ID" VARCHAR2(120 CHAR), 
	"IP" VARCHAR2(200 CHAR), 
	"PASSWORD" VARCHAR2(100 CHAR), 
	"PORT" NUMBER(10,0), 
	"SID" VARCHAR2(20 CHAR), 
	"USER_NAME" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTO_SYN_PARAM
--------------------------------------------------------

  CREATE TABLE "DEMO"."AUTO_SYN_PARAM" 
   (	"ID" VARCHAR2(120 CHAR), 
	"FROM_COL" NUMBER(10,0), 
	"PAR_NAME" VARCHAR2(200 CHAR), 
	"PAR_VALUE" VARCHAR2(600 CHAR), 
	"TO_COL" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTO_SYN_TB_PARAM
--------------------------------------------------------

  CREATE TABLE "DEMO"."AUTO_SYN_TB_PARAM" 
   (	"ID" VARCHAR2(120 CHAR), 
	"DB_ID" NUMBER(10,0), 
	"ORDER_ID" NUMBER(10,0), 
	"TABLE_NAME" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COUNTRY
--------------------------------------------------------

  CREATE TABLE "DEMO"."COUNTRY" 
   (	"CODE" VARCHAR2(120 CHAR), 
	"NAME" VARCHAR2(150 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "DEMO"."DEPARTMENT" 
   (	"DEPT_ID" VARCHAR2(120 CHAR), 
	"ADDRESS" VARCHAR2(1000 CHAR), 
	"CODE" VARCHAR2(100 CHAR), 
	"DEPT_NAME" VARCHAR2(300 CHAR), 
	"DESCRIPTION" VARCHAR2(1500 CHAR), 
	"PROVINCE_CODE" VARCHAR2(20 CHAR), 
	"STATUS" NUMBER(1,0), 
	"TELEPHONE" VARCHAR2(40 CHAR), 
	"TYPE" NUMBER(22,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT_OBJECT_PRIV
--------------------------------------------------------

  CREATE TABLE "DEMO"."DEPT_OBJECT_PRIV" 
   (	"ID" VARCHAR2(120 CHAR), 
	"APP_ID" VARCHAR2(120 CHAR), 
	"DEPT_ID" VARCHAR2(120 CHAR), 
	"OBJECT_ID" VARCHAR2(120 CHAR), 
	"PARENT_OBJ_ID" VARCHAR2(120 CHAR), 
	"PRIV_ID" VARCHAR2(120 CHAR), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT_ROLE
--------------------------------------------------------

  CREATE TABLE "DEMO"."DEPT_ROLE" 
   (	"ID" VARCHAR2(120 CHAR), 
	"APP_ID" VARCHAR2(120 CHAR), 
	"DEPT_ID" VARCHAR2(120 CHAR), 
	"ROLE_ID" VARCHAR2(120 CHAR), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT_USER_POS
--------------------------------------------------------

  CREATE TABLE "DEMO"."DEPT_USER_POS" 
   (	"DEPT_USR_POS_ID" VARCHAR2(120 CHAR), 
	"DEPT_ID" VARCHAR2(120 CHAR), 
	"POS_ID" VARCHAR2(120 CHAR), 
	"STATUS" NUMBER(1,0), 
	"USER_ID" VARCHAR2(120 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT_USR_POS_OBJ_PRIV
--------------------------------------------------------

  CREATE TABLE "DEMO"."DEPT_USR_POS_OBJ_PRIV" 
   (	"ID" VARCHAR2(120 CHAR), 
	"DEPT_USR_POS_ID" VARCHAR2(120 CHAR), 
	"OBJECT_ID" VARCHAR2(120 CHAR), 
	"PARENT_OBJ_ID" VARCHAR2(120 CHAR), 
	"PRIV_ID" VARCHAR2(120 CHAR), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT_USR_POS_ROLE
--------------------------------------------------------

  CREATE TABLE "DEMO"."DEPT_USR_POS_ROLE" 
   (	"ID" VARCHAR2(120 CHAR), 
	"APP_ID" VARCHAR2(120 CHAR), 
	"DEPT_USR_POS_ID" VARCHAR2(120 CHAR), 
	"ROLE_ID" VARCHAR2(120 CHAR), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HILOSEQUENCES
--------------------------------------------------------

  CREATE TABLE "DEMO"."HILOSEQUENCES" 
   (	"SEQUENCENAME" VARCHAR2(120 CHAR), 
	"HIGHVALUES" NUMBER(38,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JMS_MESSAGES
--------------------------------------------------------

  CREATE TABLE "DEMO"."JMS_MESSAGES" 
   (	"MESSAGEID" NUMBER(38,0), 
	"DESTINATION" VARCHAR2(255 CHAR), 
	"MESSAGEBLOB" BLOB, 
	"TXID" NUMBER(38,0), 
	"TXOP" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("MESSAGEBLOB") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table JMS_ROLES
--------------------------------------------------------

  CREATE TABLE "DEMO"."JMS_ROLES" 
   (	"ID" VARCHAR2(120 CHAR), 
	"ROLEID" VARCHAR2(120 CHAR), 
	"USERID" VARCHAR2(120 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JMS_SUBSCRIPTIONS
--------------------------------------------------------

  CREATE TABLE "DEMO"."JMS_SUBSCRIPTIONS" 
   (	"ID" VARCHAR2(120 CHAR), 
	"CLIENTID" VARCHAR2(128 CHAR), 
	"SELECTOR" VARCHAR2(255 CHAR), 
	"SUBNAME" VARCHAR2(128 CHAR), 
	"TOPIC" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JMS_TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "DEMO"."JMS_TRANSACTIONS" 
   (	"ID" VARCHAR2(120 CHAR), 
	"TXID" NUMBER(38,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JMS_USERS
--------------------------------------------------------

  CREATE TABLE "DEMO"."JMS_USERS" 
   (	"ID" VARCHAR2(120 CHAR), 
	"CLIENTID" VARCHAR2(128 CHAR), 
	"PASSWD" VARCHAR2(120 CHAR), 
	"USERID" VARCHAR2(120 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MM_MEETING
--------------------------------------------------------

  CREATE TABLE "DEMO"."MM_MEETING" 
   (	"MEETING_ID" VARCHAR2(120 CHAR), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATOR_ID" VARCHAR2(120 CHAR), 
	"DESCRIPTION" VARCHAR2(600 CHAR), 
	"END_TIME" TIMESTAMP (6), 
	"GROUP_ID" VARCHAR2(120 CHAR), 
	"IMPORTANT" NUMBER(19,0), 
	"IS_COM_SCHEDULE" NUMBER(19,0), 
	"MAIN_MEETING" NUMBER(19,0), 
	"MEETING_COMMENT" VARCHAR2(600 CHAR), 
	"MEETING_SCOPE" NUMBER(19,0), 
	"NEED_TELECONFERENCE" NUMBER(19,0), 
	"OTHER_PARTICIPANT" VARCHAR2(600 CHAR), 
	"OTHER_PRESIDENT" VARCHAR2(600 CHAR), 
	"OTHER_ROOMS" VARCHAR2(600 CHAR), 
	"OTHER_SUPPORTER" VARCHAR2(600 CHAR), 
	"PARENT_ID" NUMBER(19,0), 
	"PRE_MEETING_TASK" VARCHAR2(600 CHAR), 
	"RECUR_END_DATE" TIMESTAMP (6), 
	"RECUR_START_DATE" TIMESTAMP (6), 
	"RECURRENCE" NUMBER(19,0), 
	"ROOM_ID" VARCHAR2(120 CHAR), 
	"START_TIME" TIMESTAMP (6), 
	"STATUS" NUMBER(10,0), 
	"SUBJECT" VARCHAR2(120 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OBJECTS
--------------------------------------------------------

  CREATE TABLE "DEMO"."OBJECTS" 
   (	"OBJECT_ID" VARCHAR2(120 CHAR), 
	"APP_ID" VARCHAR2(120 CHAR), 
	"DESCRIPTION" VARCHAR2(1500 CHAR), 
	"OBJECT_CODE" VARCHAR2(100 CHAR), 
	"OBJECT_LEVEL" NUMBER(10,0), 
	"OBJECT_NAME" VARCHAR2(800 CHAR), 
	"OBJECT_TEMPLATE" VARCHAR2(1000 CHAR), 
	"OBJECT_TYPE" VARCHAR2(1 CHAR), 
	"OBJECT_TYPE_ID" NUMBER(10,0), 
	"OBJECT_URL" VARCHAR2(1000 CHAR), 
	"ORD" NUMBER(5,0), 
	"PARENT_ID" VARCHAR2(120 CHAR), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OBJECT_IM
--------------------------------------------------------

  CREATE TABLE "DEMO"."OBJECT_IM" 
   (	"ID" VARCHAR2(120 CHAR), 
	"APP_ID" VARCHAR2(120 CHAR), 
	"DESCRIPTION" VARCHAR2(1500 CHAR), 
	"OBJECT_ID" VARCHAR2(120 CHAR), 
	"OBJECT_NAME" VARCHAR2(800 CHAR), 
	"OBJECT_TEMPLATE" VARCHAR2(1000 CHAR), 
	"OBJECT_TYPE" VARCHAR2(1 CHAR), 
	"OBJECT_URL" VARCHAR2(1000 CHAR), 
	"ORD" NUMBER(5,0), 
	"PARENT_ID" VARCHAR2(120 CHAR), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OBJECT_TYPE
--------------------------------------------------------

  CREATE TABLE "DEMO"."OBJECT_TYPE" 
   (	"ID" VARCHAR2(120 CHAR), 
	"OBJECT_TYPE" VARCHAR2(1 CHAR), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLSQL_PROFILER_DATA
--------------------------------------------------------

  CREATE TABLE "DEMO"."PLSQL_PROFILER_DATA" 
   (	"ID" VARCHAR2(120 CHAR), 
	"LINE" NUMBER(19,0), 
	"MAX_TIME" NUMBER(19,0), 
	"MIN_TIME" NUMBER(19,0), 
	"RUNID" NUMBER(19,0), 
	"SPARE1" NUMBER(19,0), 
	"SPARE2" NUMBER(19,0), 
	"SPARE3" NUMBER(19,0), 
	"SPARE4" NUMBER(19,0), 
	"TOTAL_OCCUR" NUMBER(19,0), 
	"TOTAL_TIME" NUMBER(19,0), 
	"UNIT_NUMBER" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLSQL_PROFILER_RUNS
--------------------------------------------------------

  CREATE TABLE "DEMO"."PLSQL_PROFILER_RUNS" 
   (	"RUNID" VARCHAR2(120 CHAR), 
	"RELATED_RUN" NUMBER(19,0), 
	"RUN_COMMENT" VARCHAR2(2047 CHAR), 
	"RUN_COMMENT1" VARCHAR2(2047 CHAR), 
	"RUN_DATE" TIMESTAMP (6), 
	"RUN_OWNER" VARCHAR2(32 CHAR), 
	"RUN_SYSTEM_INFO" VARCHAR2(2047 CHAR), 
	"RUN_TOTAL_TIME" NUMBER(19,0), 
	"SPARE1" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLSQL_PROFILER_UNITS
--------------------------------------------------------

  CREATE TABLE "DEMO"."PLSQL_PROFILER_UNITS" 
   (	"RUNID" VARCHAR2(120 CHAR), 
	"SPARE1" NUMBER(19,0), 
	"SPARE2" NUMBER(19,0), 
	"TOTAL_TIME" NUMBER(19,0), 
	"UNIT_NAME" VARCHAR2(32 CHAR), 
	"UNIT_NUMBER" NUMBER(19,0), 
	"UNIT_OWNER" VARCHAR2(32 CHAR), 
	"UNIT_TIMESTAMP" TIMESTAMP (6), 
	"UNIT_TYPE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSITION
--------------------------------------------------------

  CREATE TABLE "DEMO"."POSITION" 
   (	"POS_ID" VARCHAR2(120 CHAR), 
	"DESCRIPTION" VARCHAR2(1500 CHAR), 
	"POS_NAME" VARCHAR2(180 CHAR), 
	"STATUS" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRIVI_TYPE
--------------------------------------------------------

  CREATE TABLE "DEMO"."PRIVI_TYPE" 
   (	"PRIV_ID" VARCHAR2(120 CHAR), 
	"DESCRIPTION" VARCHAR2(600 CHAR), 
	"OBJ_TYPE" VARCHAR2(1 CHAR), 
	"PRIORITY" NUMBER(2,0), 
	"PRIV_NAME" VARCHAR2(100 CHAR), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROVINCE
--------------------------------------------------------

  CREATE TABLE "DEMO"."PROVINCE" 
   (	"ID" VARCHAR2(120 CHAR), 
	"CENTER" NUMBER(10,0), 
	"CODE" VARCHAR2(10 CHAR), 
	"NAME" VARCHAR2(150 CHAR), 
	"STATUS" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table QUEST_SL_TEMP_EXPLAIN1
--------------------------------------------------------

  CREATE TABLE "DEMO"."QUEST_SL_TEMP_EXPLAIN1" 
   (	"ID" VARCHAR2(120 CHAR), 
	"ACCESS_PREDICATES" VARCHAR2(4000 CHAR), 
	"BYTES" NUMBER(19,0), 
	"CARDINALITY" NUMBER(19,0), 
	"COST" NUMBER(19,0), 
	"CPU_COST" NUMBER(38,0), 
	"DEPTH" NUMBER(19,0), 
	"DISTRIBUTION" VARCHAR2(30 CHAR), 
	"FILTER_PREDICATES" VARCHAR2(4000 CHAR), 
	"IO_COST" NUMBER(38,0), 
	"OBJECT_ALIAS" VARCHAR2(65 CHAR), 
	"OBJECT_INSTANCE" NUMBER(19,0), 
	"OBJECT_NAME" VARCHAR2(30 CHAR), 
	"OBJECT_NODE" VARCHAR2(128 CHAR), 
	"OBJECT_OWNER" VARCHAR2(30 CHAR), 
	"OBJECT_TYPE" VARCHAR2(30 CHAR), 
	"OPERATION" VARCHAR2(30 CHAR), 
	"OPTIMIZER" VARCHAR2(255 CHAR), 
	"OPTIONS" VARCHAR2(255 CHAR), 
	"OTHER" RAW(255), 
	"OTHER_TAG" VARCHAR2(255 CHAR), 
	"PARENT_ID" VARCHAR2(255 CHAR), 
	"PARTITION_ID" VARCHAR2(255 CHAR), 
	"PARTITION_START" VARCHAR2(255 CHAR), 
	"PARTITION_STOP" VARCHAR2(255 CHAR), 
	"PLAN_ID" VARCHAR2(255 CHAR), 
	"POSITION" NUMBER(19,0), 
	"REMARKS" VARCHAR2(80 CHAR), 
	"SEARCH_COLUMNS" NUMBER(19,0), 
	"STATEMENT_ID" VARCHAR2(30 CHAR), 
	"TEMP_SPACE" NUMBER(38,0), 
	"TIMESTAMP" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "DEMO"."ROLES" 
   (	"APP_ID" VARCHAR2(40 BYTE), 
	"DESCRIPTION" VARCHAR2(2600 BYTE), 
	"OBJ_TYPE" VARCHAR2(1 BYTE), 
	"ROLE_ID" VARCHAR2(120 BYTE), 
	"ROLE_NAME" VARCHAR2(600 BYTE), 
	"STATUS" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLE_OBJECT_PRIV
--------------------------------------------------------

  CREATE TABLE "DEMO"."ROLE_OBJECT_PRIV" 
   (	"ID" VARCHAR2(120 CHAR), 
	"OBJECT_ID" VARCHAR2(120 CHAR), 
	"PARENT_OBJ_ID" VARCHAR2(120 CHAR), 
	"PRIV_ID" VARCHAR2(1200 CHAR), 
	"ROLE_ID" VARCHAR2(120 CHAR), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLE_OBJECT_PRIV_IM
--------------------------------------------------------

  CREATE TABLE "DEMO"."ROLE_OBJECT_PRIV_IM" 
   (	"ID" VARCHAR2(120 CHAR), 
	"OBJECT_ID" VARCHAR2(120 CHAR), 
	"PARENT_OBJ_ID" VARCHAR2(120 CHAR), 
	"PRIV_ID" VARCHAR2(120 CHAR), 
	"ROLE_ID" VARCHAR2(120 CHAR), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLE_ROLE
--------------------------------------------------------

  CREATE TABLE "DEMO"."ROLE_ROLE" 
   (	"ID" VARCHAR2(120 CHAR), 
	"APP_ID" VARCHAR2(120 CHAR), 
	"DESCRIPTION" VARCHAR2(120 CHAR), 
	"OBJ_TYPE" VARCHAR2(1 CHAR), 
	"ROLE_ID" VARCHAR2(120 CHAR), 
	"ROLE_NAME" VARCHAR2(300 CHAR), 
	"STATUS" NUMBER(1,0), 
	"SUB_ROLE_ID" VARCHAR2(120 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SQLN_EXPLAIN_PLAN
--------------------------------------------------------

  CREATE TABLE "DEMO"."SQLN_EXPLAIN_PLAN" 
   (	"ID" VARCHAR2(120 CHAR), 
	"BYTES" NUMBER(38,0), 
	"CARDINALITY" NUMBER(38,0), 
	"COST" NUMBER(38,0), 
	"DISTRIBUTION" VARCHAR2(30 CHAR), 
	"OBJECT_INSTANCE" NUMBER(38,0), 
	"OBJECT_NAME" VARCHAR2(30 CHAR), 
	"OBJECT_NODE" VARCHAR2(128 CHAR), 
	"OBJECT_OWNER" VARCHAR2(30 CHAR), 
	"OBJECT_TYPE" VARCHAR2(30 CHAR), 
	"OPERATION" VARCHAR2(30 CHAR), 
	"OPTIMIZER" VARCHAR2(255 CHAR), 
	"OPTIONS" VARCHAR2(30 CHAR), 
	"OTHER" RAW(255), 
	"OTHER_TAG" VARCHAR2(255 CHAR), 
	"PARENT_ID" VARCHAR2(120 CHAR), 
	"PARTITION_ID" VARCHAR2(120 CHAR), 
	"PARTITION_START" VARCHAR2(255 CHAR), 
	"PARTITION_STOP" VARCHAR2(255 CHAR), 
	"POSITION" NUMBER(38,0), 
	"REMARKS" VARCHAR2(80 CHAR), 
	"SEARCH_COLUMNS" NUMBER(38,0), 
	"STATEMENT_ID" VARCHAR2(30 CHAR), 
	"TIMESTAMP" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SQLN_PROF_ANB
--------------------------------------------------------

  CREATE TABLE "DEMO"."SQLN_PROF_ANB" 
   (	"ID" VARCHAR2(120 CHAR), 
	"LINE" NUMBER(19,0), 
	"RUNID" VARCHAR2(120 CHAR), 
	"TEXT" VARCHAR2(2048 CHAR), 
	"UNIT_NUMBER" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SQLN_PROF_PROFILES
--------------------------------------------------------

  CREATE TABLE "DEMO"."SQLN_PROF_PROFILES" 
   (	"PROJ_ID" VARCHAR2(120 CHAR), 
	"PROJ_COMMENT" VARCHAR2(2047 CHAR), 
	"PROJ_NAME" VARCHAR2(2047 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SQLN_PROF_RUNS
--------------------------------------------------------

  CREATE TABLE "DEMO"."SQLN_PROF_RUNS" 
   (	"ID" VARCHAR2(120 CHAR), 
	"PROJ_ID" VARCHAR2(120 CHAR), 
	"RUNID" VARCHAR2(120 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SQLN_PROF_SESS
--------------------------------------------------------

  CREATE TABLE "DEMO"."SQLN_PROF_SESS" 
   (	"ID" VARCHAR2(120 CHAR), 
	"RUNID" VARCHAR2(120 CHAR), 
	"STAT_ID" VARCHAR2(120 CHAR), 
	"VALUE" NUMBER(38,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SQLN_PROF_UNITS
--------------------------------------------------------

  CREATE TABLE "DEMO"."SQLN_PROF_UNITS" 
   (	"ID" VARCHAR2(120 CHAR), 
	"PROJ_ID" VARCHAR2(120 CHAR), 
	"UNIT_NAME" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SQLN_PROF_UNIT_HASH
--------------------------------------------------------

  CREATE TABLE "DEMO"."SQLN_PROF_UNIT_HASH" 
   (	"ID" VARCHAR2(120 CHAR), 
	"HASH" VARCHAR2(32 CHAR), 
	"RUNID" VARCHAR2(120 CHAR), 
	"UNIT_NUMBER" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TMP
--------------------------------------------------------

  CREATE TABLE "DEMO"."TMP" 
   (	"ID" VARCHAR2(120 CHAR), 
	"CODE" VARCHAR2(80 CHAR), 
	"ORD" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TREES
--------------------------------------------------------

  CREATE TABLE "DEMO"."TREES" 
   (	"ID" VARCHAR2(120 CHAR), 
	"DEPT_ID" VARCHAR2(120 CHAR), 
	"PARENT_GROUP_ID" VARCHAR2(120 CHAR), 
	"TREE_ID" VARCHAR2(120 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TREE_APP
--------------------------------------------------------

  CREATE TABLE "DEMO"."TREE_APP" 
   (	"ID" VARCHAR2(120 CHAR), 
	"APP_ID" VARCHAR2(120 CHAR), 
	"TREE_ID" VARCHAR2(120 CHAR), 
	"TYPE" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TREE_INFO
--------------------------------------------------------

  CREATE TABLE "DEMO"."TREE_INFO" 
   (	"ID" VARCHAR2(120 CHAR), 
	"STATUS" NUMBER(1,0), 
	"TREE_ID" VARCHAR2(120 CHAR), 
	"TREE_NAME" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "DEMO"."USERS" 
   (	"USER_ID" VARCHAR2(120 CHAR), 
	"ALIAS_NAME" VARCHAR2(50 CHAR), 
	"BIRTH_PLACE" VARCHAR2(500 CHAR), 
	"CELLPHONE" VARCHAR2(20 CHAR), 
	"DATE_OF_BIRTH" TIMESTAMP (6), 
	"EMAIL" VARCHAR2(100 CHAR), 
	"FAX" VARCHAR2(10 CHAR), 
	"FULL_NAME" VARCHAR2(180 CHAR), 
	"GENDER" NUMBER(1,0), 
	"ID_CARD" VARCHAR2(255 CHAR), 
	"IDENTITY_CARD" VARCHAR2(15 CHAR), 
	"ISSUE_DATE_IDENT" TIMESTAMP (6), 
	"ISSUE_DATE_PASSPORT" TIMESTAMP (6), 
	"ISSUE_PLACE_IDENT" VARCHAR2(100 CHAR), 
	"ISSUE_PLACE_PASSPORT" VARCHAR2(100 CHAR), 
	"LAST_BLOCK_DATE" TIMESTAMP (6), 
	"LAST_CHANGE_PASSWORD" TIMESTAMP (6), 
	"LOGIN_FAILURE_COUNT" NUMBER(5,0), 
	"NATION_ID" NUMBER(5,0), 
	"NATIONALITY" VARCHAR2(30 CHAR), 
	"NATIVE_COUNTRY" VARCHAR2(100 CHAR), 
	"PASSPORT_NUMBER" VARCHAR2(20 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"PASSWORD_EXPIRE_STATUS" NUMBER(1,0), 
	"PASSWORDCHANGED" VARCHAR2(20 CHAR), 
	"PROVINCE_CODE" VARCHAR2(15 CHAR), 
	"RELIGION_ID" NUMBER(2,0), 
	"STATUS" NUMBER(1,0), 
	"TELEPHONE" VARCHAR2(20 CHAR), 
	"TYPE_OF_WORK" NUMBER(2,0), 
	"URL_IMAGE" VARCHAR2(255 CHAR), 
	"USER_NAME" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS_BK
--------------------------------------------------------

  CREATE TABLE "DEMO"."USERS_BK" 
   (	"ID" VARCHAR2(120 CHAR), 
	"ALIAS_NAME" VARCHAR2(50 CHAR), 
	"BIRTH_PLACE" VARCHAR2(100 CHAR), 
	"CELLPHONE" VARCHAR2(20 CHAR), 
	"DATE_OF_BIRTH" TIMESTAMP (6), 
	"EMAIL" VARCHAR2(50 CHAR), 
	"FAX" VARCHAR2(10 CHAR), 
	"FULL_NAME" VARCHAR2(180 CHAR), 
	"GENDER" NUMBER(1,0), 
	"IDENTITY_CARD" VARCHAR2(15 CHAR), 
	"ISSUE_DATE_IDENT" TIMESTAMP (6), 
	"ISSUE_DATE_PASSPORT" TIMESTAMP (6), 
	"ISSUE_PLACE_IDENT" VARCHAR2(100 CHAR), 
	"ISSUE_PLACE_PASSPORT" VARCHAR2(100 CHAR), 
	"LAST_BLOCK_DATE" TIMESTAMP (6), 
	"LAST_CHANGE_PASSWORD" TIMESTAMP (6), 
	"LOGIN_FAILURE_COUNT" NUMBER(5,0), 
	"NATION_ID" NUMBER(5,0), 
	"NATIONALITY" VARCHAR2(15 CHAR), 
	"NATIVE_COUNTRY" VARCHAR2(100 CHAR), 
	"PASSPORT_NUMBER" VARCHAR2(20 CHAR), 
	"PASSWORD" VARCHAR2(100 CHAR), 
	"PASSWORD_EXPIRE_STATUS" NUMBER(1,0), 
	"PROVINCE_CODE" VARCHAR2(15 CHAR), 
	"RELIGION_ID" NUMBER(2,0), 
	"STATUS" NUMBER(1,0), 
	"TELEPHONE" VARCHAR2(10 CHAR), 
	"TYPE_OF_WORK" NUMBER(2,0), 
	"URL_IMAGE" VARCHAR2(255 CHAR), 
	"USER_ID" VARCHAR2(120 CHAR), 
	"USER_NAME" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UTIL_ATTACKED_DOCUMENTS
--------------------------------------------------------

  CREATE TABLE "DEMO"."UTIL_ATTACKED_DOCUMENTS" 
   (	"ID" VARCHAR2(120 CHAR), 
	"ATTACH_ID" VARCHAR2(120 CHAR), 
	"CODE" VARCHAR2(20 CHAR), 
	"CREATED_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(600 CHAR), 
	"DOC_SOURCE_TYPE" NUMBER(10,0), 
	"DOCUMENT_NAME" VARCHAR2(20 CHAR), 
	"DOCUMENT_PATH" VARCHAR2(20 CHAR), 
	"LEVEL_ID" NUMBER(10,0), 
	"PARENT_ID" VARCHAR2(120 CHAR), 
	"SIGNED_DATE" TIMESTAMP (6), 
	"SIGNER" VARCHAR2(20 CHAR), 
	"UPLOADER_ID" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into DEMO.ACTION_LOG
SET DEFINE OFF;
REM INSERTING into DEMO.APPLICATIONS
SET DEFINE OFF;
REM INSERTING into DEMO.AREA
SET DEFINE OFF;
REM INSERTING into DEMO.AUTO_SYN_DATA
SET DEFINE OFF;
REM INSERTING into DEMO.AUTO_SYN_DB_PARAM
SET DEFINE OFF;
REM INSERTING into DEMO.AUTO_SYN_PARAM
SET DEFINE OFF;
REM INSERTING into DEMO.AUTO_SYN_TB_PARAM
SET DEFINE OFF;
REM INSERTING into DEMO.COUNTRY
SET DEFINE OFF;
REM INSERTING into DEMO.DEPARTMENT
SET DEFINE OFF;
REM INSERTING into DEMO.DEPT_OBJECT_PRIV
SET DEFINE OFF;
REM INSERTING into DEMO.DEPT_ROLE
SET DEFINE OFF;
REM INSERTING into DEMO.DEPT_USER_POS
SET DEFINE OFF;
REM INSERTING into DEMO.DEPT_USR_POS_OBJ_PRIV
SET DEFINE OFF;
REM INSERTING into DEMO.DEPT_USR_POS_ROLE
SET DEFINE OFF;
REM INSERTING into DEMO.HILOSEQUENCES
SET DEFINE OFF;
REM INSERTING into DEMO.JMS_MESSAGES
SET DEFINE OFF;
REM INSERTING into DEMO.JMS_ROLES
SET DEFINE OFF;
REM INSERTING into DEMO.JMS_SUBSCRIPTIONS
SET DEFINE OFF;
REM INSERTING into DEMO.JMS_TRANSACTIONS
SET DEFINE OFF;
REM INSERTING into DEMO.JMS_USERS
SET DEFINE OFF;
REM INSERTING into DEMO.MM_MEETING
SET DEFINE OFF;
REM INSERTING into DEMO.OBJECTS
SET DEFINE OFF;
REM INSERTING into DEMO.OBJECT_IM
SET DEFINE OFF;
REM INSERTING into DEMO.OBJECT_TYPE
SET DEFINE OFF;
REM INSERTING into DEMO.PLSQL_PROFILER_DATA
SET DEFINE OFF;
REM INSERTING into DEMO.PLSQL_PROFILER_RUNS
SET DEFINE OFF;
REM INSERTING into DEMO.PLSQL_PROFILER_UNITS
SET DEFINE OFF;
REM INSERTING into DEMO.POSITION
SET DEFINE OFF;
REM INSERTING into DEMO.PRIVI_TYPE
SET DEFINE OFF;
REM INSERTING into DEMO.PROVINCE
SET DEFINE OFF;
REM INSERTING into DEMO.QUEST_SL_TEMP_EXPLAIN1
SET DEFINE OFF;
REM INSERTING into DEMO.ROLES
SET DEFINE OFF;
REM INSERTING into DEMO.ROLE_OBJECT_PRIV
SET DEFINE OFF;
REM INSERTING into DEMO.ROLE_OBJECT_PRIV_IM
SET DEFINE OFF;
REM INSERTING into DEMO.ROLE_ROLE
SET DEFINE OFF;
REM INSERTING into DEMO.SQLN_EXPLAIN_PLAN
SET DEFINE OFF;
REM INSERTING into DEMO.SQLN_PROF_ANB
SET DEFINE OFF;
REM INSERTING into DEMO.SQLN_PROF_PROFILES
SET DEFINE OFF;
REM INSERTING into DEMO.SQLN_PROF_RUNS
SET DEFINE OFF;
REM INSERTING into DEMO.SQLN_PROF_SESS
SET DEFINE OFF;
REM INSERTING into DEMO.SQLN_PROF_UNITS
SET DEFINE OFF;
REM INSERTING into DEMO.SQLN_PROF_UNIT_HASH
SET DEFINE OFF;
REM INSERTING into DEMO.TMP
SET DEFINE OFF;
REM INSERTING into DEMO.TREES
SET DEFINE OFF;
REM INSERTING into DEMO.TREE_APP
SET DEFINE OFF;
REM INSERTING into DEMO.TREE_INFO
SET DEFINE OFF;
REM INSERTING into DEMO.USERS
SET DEFINE OFF;
REM INSERTING into DEMO.USERS_BK
SET DEFINE OFF;
REM INSERTING into DEMO.UTIL_ATTACKED_DOCUMENTS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."ROLES_PK" ON "DEMO"."ROLES" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007422
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007422" ON "DEMO"."UTIL_ATTACKED_DOCUMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007424
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007424" ON "DEMO"."POSITION" ("POS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007426
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007426" ON "DEMO"."DEPT_OBJECT_PRIV" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007428
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007428" ON "DEMO"."OBJECTS" ("OBJECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007430
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007430" ON "DEMO"."DEPT_ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007432
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007432" ON "DEMO"."JMS_ROLES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007434
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007434" ON "DEMO"."MM_MEETING" ("MEETING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007436
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007436" ON "DEMO"."USERS_BK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007438
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007438" ON "DEMO"."TREE_APP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007440
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007440" ON "DEMO"."DEPT_USR_POS_ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007442
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007442" ON "DEMO"."SQLN_PROF_SESS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007444
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007444" ON "DEMO"."DEPT_USR_POS_OBJ_PRIV" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007446
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007446" ON "DEMO"."ROLE_ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007448
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007448" ON "DEMO"."SQLN_PROF_RUNS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007450
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007450" ON "DEMO"."HILOSEQUENCES" ("SEQUENCENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007452
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007452" ON "DEMO"."SQLN_EXPLAIN_PLAN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007454
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007454" ON "DEMO"."PLSQL_PROFILER_UNITS" ("RUNID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007456
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007456" ON "DEMO"."OBJECT_IM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007458
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007458" ON "DEMO"."ACTION_LOG" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007460
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007460" ON "DEMO"."SQLN_PROF_UNIT_HASH" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007462
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007462" ON "DEMO"."PRIVI_TYPE" ("PRIV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007464
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007464" ON "DEMO"."PROVINCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007466
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007466" ON "DEMO"."COUNTRY" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007468
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007468" ON "DEMO"."DEPT_USER_POS" ("DEPT_USR_POS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007470
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007470" ON "DEMO"."SQLN_PROF_PROFILES" ("PROJ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007472
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007472" ON "DEMO"."QUEST_SL_TEMP_EXPLAIN1" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007474
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007474" ON "DEMO"."AUTO_SYN_PARAM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007476
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007476" ON "DEMO"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007478
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007478" ON "DEMO"."PLSQL_PROFILER_DATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007482
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007482" ON "DEMO"."AREA" ("AREA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007485
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007485" ON "DEMO"."JMS_TRANSACTIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007487
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007487" ON "DEMO"."AUTO_SYN_TB_PARAM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007489
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007489" ON "DEMO"."ROLE_OBJECT_PRIV" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007491
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007491" ON "DEMO"."TREES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007493
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007493" ON "DEMO"."APPLICATIONS" ("APP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007495
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007495" ON "DEMO"."AUTO_SYN_DATA" ("DB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007497
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007497" ON "DEMO"."SQLN_PROF_UNITS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007499
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007499" ON "DEMO"."AUTO_SYN_DB_PARAM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007501
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007501" ON "DEMO"."TREE_INFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007503
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007503" ON "DEMO"."SQLN_PROF_ANB" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007507
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007507" ON "DEMO"."PLSQL_PROFILER_RUNS" ("RUNID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007509
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007509" ON "DEMO"."JMS_SUBSCRIPTIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007511
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007511" ON "DEMO"."JMS_USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007513
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007513" ON "DEMO"."ROLE_OBJECT_PRIV_IM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007515
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007515" ON "DEMO"."DEPARTMENT" ("DEPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007517
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007517" ON "DEMO"."JMS_MESSAGES" ("MESSAGEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007519
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007519" ON "DEMO"."TMP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007521
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007521" ON "DEMO"."OBJECT_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073093C00003$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_IL0000073093C00003$$" ON "DEMO"."JMS_MESSAGES" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_C007458
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007458" ON "DEMO"."ACTION_LOG" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007493
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007493" ON "DEMO"."APPLICATIONS" ("APP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007482
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007482" ON "DEMO"."AREA" ("AREA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007495
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007495" ON "DEMO"."AUTO_SYN_DATA" ("DB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007499
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007499" ON "DEMO"."AUTO_SYN_DB_PARAM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007474
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007474" ON "DEMO"."AUTO_SYN_PARAM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007487
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007487" ON "DEMO"."AUTO_SYN_TB_PARAM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007466
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007466" ON "DEMO"."COUNTRY" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007515
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007515" ON "DEMO"."DEPARTMENT" ("DEPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007426
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007426" ON "DEMO"."DEPT_OBJECT_PRIV" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007430
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007430" ON "DEMO"."DEPT_ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007468
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007468" ON "DEMO"."DEPT_USER_POS" ("DEPT_USR_POS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007444
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007444" ON "DEMO"."DEPT_USR_POS_OBJ_PRIV" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007440
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007440" ON "DEMO"."DEPT_USR_POS_ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007450
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007450" ON "DEMO"."HILOSEQUENCES" ("SEQUENCENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007517
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007517" ON "DEMO"."JMS_MESSAGES" ("MESSAGEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007432
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007432" ON "DEMO"."JMS_ROLES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007509
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007509" ON "DEMO"."JMS_SUBSCRIPTIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007485
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007485" ON "DEMO"."JMS_TRANSACTIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007511
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007511" ON "DEMO"."JMS_USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007434
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007434" ON "DEMO"."MM_MEETING" ("MEETING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007428
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007428" ON "DEMO"."OBJECTS" ("OBJECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007456
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007456" ON "DEMO"."OBJECT_IM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007521
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007521" ON "DEMO"."OBJECT_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007478
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007478" ON "DEMO"."PLSQL_PROFILER_DATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007507
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007507" ON "DEMO"."PLSQL_PROFILER_RUNS" ("RUNID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007454
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007454" ON "DEMO"."PLSQL_PROFILER_UNITS" ("RUNID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007424
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007424" ON "DEMO"."POSITION" ("POS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007462
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007462" ON "DEMO"."PRIVI_TYPE" ("PRIV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007464
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007464" ON "DEMO"."PROVINCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007472
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007472" ON "DEMO"."QUEST_SL_TEMP_EXPLAIN1" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."ROLES_PK" ON "DEMO"."ROLES" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007489
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007489" ON "DEMO"."ROLE_OBJECT_PRIV" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007513
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007513" ON "DEMO"."ROLE_OBJECT_PRIV_IM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007446
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007446" ON "DEMO"."ROLE_ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007452
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007452" ON "DEMO"."SQLN_EXPLAIN_PLAN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007503
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007503" ON "DEMO"."SQLN_PROF_ANB" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007470
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007470" ON "DEMO"."SQLN_PROF_PROFILES" ("PROJ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007448
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007448" ON "DEMO"."SQLN_PROF_RUNS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007442
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007442" ON "DEMO"."SQLN_PROF_SESS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007497
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007497" ON "DEMO"."SQLN_PROF_UNITS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007460
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007460" ON "DEMO"."SQLN_PROF_UNIT_HASH" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007519
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007519" ON "DEMO"."TMP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007491
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007491" ON "DEMO"."TREES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007438
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007438" ON "DEMO"."TREE_APP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007501
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007501" ON "DEMO"."TREE_INFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007476
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007476" ON "DEMO"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007436
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007436" ON "DEMO"."USERS_BK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007422
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."SYS_C007422" ON "DEMO"."UTIL_ATTACKED_DOCUMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Package PACKAGE1
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "DEMO"."PACKAGE1" AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 
function afdUser(
pid nvarchar2,
pabc nvarchar2

)
return nvarchar2;



END PACKAGE1;

/
--------------------------------------------------------
--  DDL for Package Body PACKAGE1
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "DEMO"."PACKAGE1" AS

  function afdUser(
pid nvarchar2,
pabc nvarchar2
)
return nvarchar2 AS
s nvarchar2(4000);

  BEGIN
  
    s := 'insert a,b value (:a,:b) ';
    -- TODO: Implementation required for function PACKAGE1.afdUser
    RETURN null;
  END;

END PACKAGE1;

/
--------------------------------------------------------
--  Constraints for Table ACTION_LOG
--------------------------------------------------------

  ALTER TABLE "DEMO"."ACTION_LOG" MODIFY ("LOG_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."ACTION_LOG" ADD PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table APPLICATIONS
--------------------------------------------------------

  ALTER TABLE "DEMO"."APPLICATIONS" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."APPLICATIONS" ADD PRIMARY KEY ("APP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AREA
--------------------------------------------------------

  ALTER TABLE "DEMO"."AREA" MODIFY ("AREA_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."AREA" ADD PRIMARY KEY ("AREA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTO_SYN_DATA
--------------------------------------------------------

  ALTER TABLE "DEMO"."AUTO_SYN_DATA" MODIFY ("DB_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."AUTO_SYN_DATA" ADD PRIMARY KEY ("DB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTO_SYN_DB_PARAM
--------------------------------------------------------

  ALTER TABLE "DEMO"."AUTO_SYN_DB_PARAM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."AUTO_SYN_DB_PARAM" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTO_SYN_PARAM
--------------------------------------------------------

  ALTER TABLE "DEMO"."AUTO_SYN_PARAM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."AUTO_SYN_PARAM" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTO_SYN_TB_PARAM
--------------------------------------------------------

  ALTER TABLE "DEMO"."AUTO_SYN_TB_PARAM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."AUTO_SYN_TB_PARAM" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COUNTRY
--------------------------------------------------------

  ALTER TABLE "DEMO"."COUNTRY" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."COUNTRY" ADD PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "DEMO"."DEPARTMENT" MODIFY ("DEPT_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."DEPARTMENT" ADD PRIMARY KEY ("DEPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPT_OBJECT_PRIV
--------------------------------------------------------

  ALTER TABLE "DEMO"."DEPT_OBJECT_PRIV" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."DEPT_OBJECT_PRIV" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPT_ROLE
--------------------------------------------------------

  ALTER TABLE "DEMO"."DEPT_ROLE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."DEPT_ROLE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPT_USER_POS
--------------------------------------------------------

  ALTER TABLE "DEMO"."DEPT_USER_POS" MODIFY ("DEPT_USR_POS_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."DEPT_USER_POS" ADD PRIMARY KEY ("DEPT_USR_POS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPT_USR_POS_OBJ_PRIV
--------------------------------------------------------

  ALTER TABLE "DEMO"."DEPT_USR_POS_OBJ_PRIV" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."DEPT_USR_POS_OBJ_PRIV" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPT_USR_POS_ROLE
--------------------------------------------------------

  ALTER TABLE "DEMO"."DEPT_USR_POS_ROLE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."DEPT_USR_POS_ROLE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HILOSEQUENCES
--------------------------------------------------------

  ALTER TABLE "DEMO"."HILOSEQUENCES" MODIFY ("SEQUENCENAME" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."HILOSEQUENCES" ADD PRIMARY KEY ("SEQUENCENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JMS_MESSAGES
--------------------------------------------------------

  ALTER TABLE "DEMO"."JMS_MESSAGES" MODIFY ("MESSAGEID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."JMS_MESSAGES" ADD PRIMARY KEY ("MESSAGEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JMS_ROLES
--------------------------------------------------------

  ALTER TABLE "DEMO"."JMS_ROLES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."JMS_ROLES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JMS_SUBSCRIPTIONS
--------------------------------------------------------

  ALTER TABLE "DEMO"."JMS_SUBSCRIPTIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."JMS_SUBSCRIPTIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JMS_TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "DEMO"."JMS_TRANSACTIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."JMS_TRANSACTIONS" MODIFY ("TXID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."JMS_TRANSACTIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JMS_USERS
--------------------------------------------------------

  ALTER TABLE "DEMO"."JMS_USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."JMS_USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MM_MEETING
--------------------------------------------------------

  ALTER TABLE "DEMO"."MM_MEETING" MODIFY ("MEETING_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."MM_MEETING" ADD PRIMARY KEY ("MEETING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OBJECTS
--------------------------------------------------------

  ALTER TABLE "DEMO"."OBJECTS" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."OBJECTS" ADD PRIMARY KEY ("OBJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OBJECT_IM
--------------------------------------------------------

  ALTER TABLE "DEMO"."OBJECT_IM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."OBJECT_IM" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OBJECT_TYPE
--------------------------------------------------------

  ALTER TABLE "DEMO"."OBJECT_TYPE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."OBJECT_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLSQL_PROFILER_DATA
--------------------------------------------------------

  ALTER TABLE "DEMO"."PLSQL_PROFILER_DATA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."PLSQL_PROFILER_DATA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLSQL_PROFILER_RUNS
--------------------------------------------------------

  ALTER TABLE "DEMO"."PLSQL_PROFILER_RUNS" MODIFY ("RUNID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."PLSQL_PROFILER_RUNS" ADD PRIMARY KEY ("RUNID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLSQL_PROFILER_UNITS
--------------------------------------------------------

  ALTER TABLE "DEMO"."PLSQL_PROFILER_UNITS" MODIFY ("RUNID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."PLSQL_PROFILER_UNITS" ADD PRIMARY KEY ("RUNID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POSITION
--------------------------------------------------------

  ALTER TABLE "DEMO"."POSITION" MODIFY ("POS_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."POSITION" ADD PRIMARY KEY ("POS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRIVI_TYPE
--------------------------------------------------------

  ALTER TABLE "DEMO"."PRIVI_TYPE" MODIFY ("PRIV_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."PRIVI_TYPE" ADD PRIMARY KEY ("PRIV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVINCE
--------------------------------------------------------

  ALTER TABLE "DEMO"."PROVINCE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."PROVINCE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUEST_SL_TEMP_EXPLAIN1
--------------------------------------------------------

  ALTER TABLE "DEMO"."QUEST_SL_TEMP_EXPLAIN1" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."QUEST_SL_TEMP_EXPLAIN1" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "DEMO"."ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX "DEMO"."ROLES_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE_OBJECT_PRIV
--------------------------------------------------------

  ALTER TABLE "DEMO"."ROLE_OBJECT_PRIV" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."ROLE_OBJECT_PRIV" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE_OBJECT_PRIV_IM
--------------------------------------------------------

  ALTER TABLE "DEMO"."ROLE_OBJECT_PRIV_IM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."ROLE_OBJECT_PRIV_IM" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE_ROLE
--------------------------------------------------------

  ALTER TABLE "DEMO"."ROLE_ROLE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."ROLE_ROLE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SQLN_EXPLAIN_PLAN
--------------------------------------------------------

  ALTER TABLE "DEMO"."SQLN_EXPLAIN_PLAN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."SQLN_EXPLAIN_PLAN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SQLN_PROF_ANB
--------------------------------------------------------

  ALTER TABLE "DEMO"."SQLN_PROF_ANB" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."SQLN_PROF_ANB" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SQLN_PROF_PROFILES
--------------------------------------------------------

  ALTER TABLE "DEMO"."SQLN_PROF_PROFILES" MODIFY ("PROJ_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."SQLN_PROF_PROFILES" ADD PRIMARY KEY ("PROJ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SQLN_PROF_RUNS
--------------------------------------------------------

  ALTER TABLE "DEMO"."SQLN_PROF_RUNS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."SQLN_PROF_RUNS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SQLN_PROF_SESS
--------------------------------------------------------

  ALTER TABLE "DEMO"."SQLN_PROF_SESS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."SQLN_PROF_SESS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SQLN_PROF_UNITS
--------------------------------------------------------

  ALTER TABLE "DEMO"."SQLN_PROF_UNITS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."SQLN_PROF_UNITS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SQLN_PROF_UNIT_HASH
--------------------------------------------------------

  ALTER TABLE "DEMO"."SQLN_PROF_UNIT_HASH" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."SQLN_PROF_UNIT_HASH" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TMP
--------------------------------------------------------

  ALTER TABLE "DEMO"."TMP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."TMP" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TREES
--------------------------------------------------------

  ALTER TABLE "DEMO"."TREES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."TREES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TREE_APP
--------------------------------------------------------

  ALTER TABLE "DEMO"."TREE_APP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."TREE_APP" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TREE_INFO
--------------------------------------------------------

  ALTER TABLE "DEMO"."TREE_INFO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."TREE_INFO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "DEMO"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS_BK
--------------------------------------------------------

  ALTER TABLE "DEMO"."USERS_BK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."USERS_BK" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UTIL_ATTACKED_DOCUMENTS
--------------------------------------------------------

  ALTER TABLE "DEMO"."UTIL_ATTACKED_DOCUMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."UTIL_ATTACKED_DOCUMENTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPT_OBJECT_PRIV
--------------------------------------------------------

  ALTER TABLE "DEMO"."DEPT_OBJECT_PRIV" ADD CONSTRAINT "FKD7JNW9I519IYRUJB3CVN96NKI" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "DEMO"."DEPARTMENT" ("DEPT_ID") ENABLE;
  ALTER TABLE "DEMO"."DEPT_OBJECT_PRIV" ADD CONSTRAINT "FKSLH2KOXWG4V2LXMAEN6SNNELT" FOREIGN KEY ("OBJECT_ID")
	  REFERENCES "DEMO"."OBJECTS" ("OBJECT_ID") ENABLE;
  ALTER TABLE "DEMO"."DEPT_OBJECT_PRIV" ADD CONSTRAINT "FKE3U864T43IVQCAXL8YV6RWOR0" FOREIGN KEY ("PRIV_ID")
	  REFERENCES "DEMO"."PRIVI_TYPE" ("PRIV_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPT_ROLE
--------------------------------------------------------

  ALTER TABLE "DEMO"."DEPT_ROLE" ADD CONSTRAINT "FKR40GOBMIF7BP72DKFWMP0CVVS" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "DEMO"."DEPARTMENT" ("DEPT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPT_USER_POS
--------------------------------------------------------

  ALTER TABLE "DEMO"."DEPT_USER_POS" ADD CONSTRAINT "FK73RHV72SCWWIJ9JRLWRMQTS1S" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "DEMO"."DEPARTMENT" ("DEPT_ID") ENABLE;
  ALTER TABLE "DEMO"."DEPT_USER_POS" ADD CONSTRAINT "FK9PAOF0MVBOT0ISW5WF4D4Q2W" FOREIGN KEY ("POS_ID")
	  REFERENCES "DEMO"."POSITION" ("POS_ID") ENABLE;
  ALTER TABLE "DEMO"."DEPT_USER_POS" ADD CONSTRAINT "FK4IR8MYV6ESMX0OLAXK6HL7AKW" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEMO"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPT_USR_POS_OBJ_PRIV
--------------------------------------------------------

  ALTER TABLE "DEMO"."DEPT_USR_POS_OBJ_PRIV" ADD CONSTRAINT "FKPS30KX4QWH8Q212KQPW607R8L" FOREIGN KEY ("DEPT_USR_POS_ID")
	  REFERENCES "DEMO"."DEPT_USER_POS" ("DEPT_USR_POS_ID") ENABLE;
  ALTER TABLE "DEMO"."DEPT_USR_POS_OBJ_PRIV" ADD CONSTRAINT "FK5XMXOY6OOUTTR8GSXB9O0T7F2" FOREIGN KEY ("OBJECT_ID")
	  REFERENCES "DEMO"."OBJECTS" ("OBJECT_ID") ENABLE;
  ALTER TABLE "DEMO"."DEPT_USR_POS_OBJ_PRIV" ADD CONSTRAINT "FKQKQWH253HOY3VXCBVIDW1FY2O" FOREIGN KEY ("PRIV_ID")
	  REFERENCES "DEMO"."PRIVI_TYPE" ("PRIV_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPT_USR_POS_ROLE
--------------------------------------------------------

  ALTER TABLE "DEMO"."DEPT_USR_POS_ROLE" ADD CONSTRAINT "FK9XFQCXTXQ96EHQ08U84RWXQ68" FOREIGN KEY ("DEPT_USR_POS_ID")
	  REFERENCES "DEMO"."DEPT_USER_POS" ("DEPT_USR_POS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OBJECTS
--------------------------------------------------------

  ALTER TABLE "DEMO"."OBJECTS" ADD CONSTRAINT "FKC45JGYKYKQ09FN159X6XRYY6Q" FOREIGN KEY ("APP_ID")
	  REFERENCES "DEMO"."APPLICATIONS" ("APP_ID") ENABLE;
  ALTER TABLE "DEMO"."OBJECTS" ADD CONSTRAINT "FKI1J1C1L3XYVXGFDCQ9FOL7W7L" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "DEMO"."OBJECTS" ("OBJECT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROLE_OBJECT_PRIV
--------------------------------------------------------

  ALTER TABLE "DEMO"."ROLE_OBJECT_PRIV" ADD CONSTRAINT "FKJIM7DJV12YRPABC980H3VNQG9" FOREIGN KEY ("OBJECT_ID")
	  REFERENCES "DEMO"."OBJECTS" ("OBJECT_ID") ENABLE;
